# Generated by Django 3.2.16 on 2022-11-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2_App', '0003_numbers_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('nickname', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
    ]
